### ISSUE TITLE
Remove hbs-helpers/framework dependency from Bechamel

### ISSUE THREAD

**Issue by elyseholladay** [RetailMeNotSandbox/bechamel#1]
see: https://github.com/RetailMeNotSandbox/roux/issues/10

We should remove the hbs-helpers dependency before OS'ing Bechamel. (Or update the reference if we open source the hbs-helpers repo @knksmith57)

**Comment by lzilioli** [comment]
moving to our internal issue tracker since this is a blocker to code landing in this github repo
