### ISSUE TITLE
try to match wrong urls 

### ISSUE THREAD

**Issue by elyseholladay** [RetailMeNotSandbox/bechamel#10]
In a pantry you can have any arbitrary subdirectories to divide up your ingredients, but Bechamel does't know what to do with those URLs. For example, if you go to `/pantries/pantry-name/subdirectory/` right now you get nothing. Instead, you should get a list of all ingredients within that subdirectory.

**Comment by lzilioli** [comment]
this is a relic of the old, non-static bechamel
