### ISSUE TITLE
load bechamel from the command line

### ISSUE THREAD

**Issue by elyseholladay** [RetailMeNotSandbox/bechamel#3]
A developer should be able to load Béchamel with any N number of the pantries she is developing against. 

For example, you could pass them in as CLI flags along the lines of:

`bechamel start --pantries A B C`

You must load at least one pantry into Béchamel; it should error if you do not. (Alternatively we could set up a config that allows you to set a default pantry to load, and use the CLI flags as additional/optional pantries.)

**Comment by knksmith57** [comment]
I know this is early planning, but after thinking about the interface, a couple of thoughts:

* multiple `--pantry` options instead of a single `--pantries` using space-delimited list
* aliasing support for names -> paths for local dev, eg: `--pantry foo:.` and `--pantry bar:./ingredients/bar`

**Comment by lzilioli** [comment]
I've got this change landed to the private bechamel repo.

It requires you provide the `name:pantry` mapping on the CLI. I think we can do better. If you just pass a path, we can glean the name from package.json.

**Comment by lzilioli** [comment]
I went ahead and coded this up. PR on y'all

**Comment by elyseholladay** [comment]
closing anticipating the OS release of static-bechamel and new CLI
